#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# ??????????? this fails on /_includes/layouts/base.njk
# exec git diff --cached --name-only | npx cspell --no-summary --no-progress --no-must-find-files --file-list stdin

# ??????????? this doesn't
npx cspell --no-summary --no-progress --no-must-find-files "**"